// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwZ6SPJAlQYtVo01Oa88WWroklL80b5w',
    appId: '1:177955513414:web:e75515ffb0cb8deac95647',
    messagingSenderId: '177955513414',
    projectId: 'ecommerceapp-7640d',
    authDomain: 'ecommerceapp-7640d.firebaseapp.com',
    storageBucket: 'ecommerceapp-7640d.firebasestorage.app',
    measurementId: 'G-VZLW63KTXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzwWnNFNB_bZMtTZoIDUch1EDl8c2HDJw',
    appId: '1:177955513414:android:57698450f32c75b2c95647',
    messagingSenderId: '177955513414',
    projectId: 'ecommerceapp-7640d',
    storageBucket: 'ecommerceapp-7640d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBa8oBE3Bb2BsafaoxG5Ygv_jZ4-Y4z64',
    appId: '1:177955513414:ios:bc5885903d56a759c95647',
    messagingSenderId: '177955513414',
    projectId: 'ecommerceapp-7640d',
    storageBucket: 'ecommerceapp-7640d.firebasestorage.app',
    androidClientId: '177955513414-mlla26e18d504ls3up271suiuipgctfj.apps.googleusercontent.com',
    iosClientId: '177955513414-odf4urdn5g4ho2c658plsgfg1iuf7rkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

}